name = "check_terminal_styles"
description = "Release and documentation checks for terminal_styles"
version = "0.1.0-dev"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["tool", "release", "check"]

executables = ["check_terminal_styles"]

[[depends-on]]
gnat_native = "=15.2.1"
project_tools = "*"

[[pins]]
project_tools = { path = "../../project_tools" }
