name = "terminal_styles_basic_example"
description = "Basic terminal_styles formatting example"
version = "0.1.0-dev"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT"
website = ""
tags = ["example", "terminal"]

executables = ["terminal_styles_basic_example"]

[[depends-on]]
gnat_native = "=15.2.1"

[[depends-on]]
terminal_styles = "*"

[[pins]]
terminal_styles = { path = "../.." }

[build-profiles]
"*" = "development"
